### ISSUE TITLE
Arm & Disarm work only on first Area

### ISSUE THREAD

**Issue by DejanBukovec** [gunkutzeybek/hikaxpro_hacs#2]
I would like report issue that integration can arm & disarm only one Area.
For example I have 3 areas each one for each floor and when I arm Alarm Panel with integration it arm only first Area(Ground Floor) and other 2 areas stay disarmed...
I think that you need to call global arm/disarm function instead of first area... Or better make option to seperate arm/disarm each Area...

**Comment by gunkutzeybek** [comment]
Hi,
Yes, right now it is hardcoded in the code to arm only first area. 
I think the areas in use can be discovered with ISAPI queries and all area ids can be added to arm command for a global arming function. 
Also as you said they can be managed separately. 
I am marking this as a enhancement. 
This issue will be picked soon when I have time.

**Comment by DejanBukovec** [comment]
Im see after Im post issue in your other repo(hikaxpro) that you have hardcoded links in file consts.py where on HAOS I can find that files? Maybe I can modify them myself or find what is global URL for arm&disarm all areas...
In documentation I found this:
![slika](https://user-images.githubusercontent.com/52787044/178233103-989f8d54-6b03-486e-af52-9e1350facfa9.png)

**Comment by DejanBukovec** [comment]
I would like to confirm that now arm&disarm work on all zones.
Thanks for fast fix.
